<?php

/**
 * Implementation of hook_menu
 */
function issuu_menu() {
  $items['admin/settings/issuu'] = array(
    'title' => 'Issuu',
    'description' => 'Setup issuu to display files as publications inline with JavaScript (http://issuu.com/smartlook)',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'issuu_admin_settings'
    ),
    'access arguments' => array(
      'administer site configuration'
    ),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'issuu.admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_nodeapi
 */
function issuu_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case "view":
      // Load types to use issuu on
      $options = variable_get('issuu_selected_types', array());
      if (in_array($node->type, array_filter($options))) {
        issuu_add();
      }
  }
}

function issuu_add() {
  // Load configuration
  $guid = variable_get('issuu_guid', NULL);
  $domain = variable_get('issuu_domain', NULL);

  // Added JavaScript to the page
  if ($guid != null && $domain != null) {    
    drupal_add_js('var issuuConfig = { guid: "' .$guid. '", domain: "' .$domain. '"};', 'inline');
    drupal_add_js(drupal_get_path('module', 'issuu'). '/issuu.js', 'module', 'footer', FALSE, FALSE, FALSE);
  }
}